import 'quote.dart';
import 'quote_source.dart';

const List<Quote> ALL_QUOTES = [
  // TV
  Quote('hustle_dodgy_git', 'You dodgy git', SRC_HUSTLE, '30 thirty grand ash danny'),
  Quote('hustle_funny_money', 'Funny money', SRC_HUSTLE, 'None of that funny money'),
  Quote('dexter_hello_dexter_morgan', 'Hello, Dexter Morgan', SRC_DEXTER, 'hello dexter morgan trinity arthur mitchell',
      'trinity'),
  Quote('dexter_lfi_on_the_bhb', 'LFI on the BHB', SRC_DEXTER, 'lfi on the bhb v2', 'vince_masuka'),
  Quote('dexter_more_comfortable', 'More comfortable', SRC_DEXTER,
      'I can get a sandwich if it makes you more comfortable', 'lundy'),
  Quote('dexter_one_o_clock', 'It\'s one o\'clock', SRC_DEXTER,
      'its one o clock i always stop and have lunch at one o clock 1 o clock 1:00', 'lundy'),
  Quote('dexter_pardon_my_tits', 'Pardon my tits', SRC_DEXTER, 'pardon my tits', 'lila'),
  Quote('dexter_reinvent_the_wheel', 'Reinvent the wheel', SRC_DEXTER,
      'maybe you should just learn the basics before you reinvent the damn wheel'),
  Quote('dexter_surprise_motherfucker', 'Surprise', SRC_DEXTER, 'surprise motherfucker motherfucka'),
  Quote('dexter_take_a_picture', 'Take a picture', SRC_DEXTER, 'why dont you take a picture morgan itll last longer'),
  Quote('dexter_tick_tick_tick', 'Tick tick tick', SRC_DEXTER,
      'tick tick tick thats the sound of your life running out', 'dexter_jordan_chase'),
  Quote('dexter_woo_woo_shit', 'Woo woo shit', SRC_DEXTER,
      'angel you keep up with this woo woo shit ima walk right through you'),
  Quote('b99_bingpot', 'Bingpot!', SRC_B99, 'bingpot'),
  Quote('b99_bingpot_2', 'Bingpot 2', SRC_B99, 'bingpot'),
  Quote('b99_bone', 'Bone', SRC_B99, 'bone'),
  Quote('b99_bone_2', 'Booooone', SRC_B99, 'bone'),
  Quote('b99_boost_my_bottom', 'Boost my bottom', SRC_B99, 'boost my bottom'),
  Quote('b99_cool_cool', 'Cool cool cool', SRC_B99, 'cool cool cool jake peralta v2', 'jake'),
  Quote('b99_hello_dolly', 'Helloooo dolly', SRC_B99, 'hello dolly'),
  Quote('b99_is_everything_ok', 'Is everything ok?', SRC_B99, 'and you ask me is everything okay'),
  Quote('b99_is_everything_ok_2', 'Is everything ok 2', SRC_B99, 'and you ask me is everything okay'),
  Quote('b99_oh_damn', 'Oh damn', SRC_B99, 'oh damn oh damn oh damn'),
  Quote('b99_pain', 'Painnnnn', SRC_B99, 'painnnn'),
  Quote('b99_velvet_thunder', 'Velvet thunder', SRC_B99, 'from now on call me velvet thunderrrr'),
  Quote('b99_vindication', 'Vindication', SRC_B99, 'vindication'),
  Quote('b99_youre_not_cheddar', 'You\'re not cheddar', SRC_B99, 'youre not cheddar youre just some common bitch'),
  Quote('dads_army_dont_like_it_up_em', 'Don\'t like it up \'em', SRC_DADS_ARMY, 'they don\'t dont like it up em'),
  Quote('dads_army_dont_panic_anyone', 'Don\'t panic', SRC_DADS_ARMY, 'don\'t dont panic anyone'),
  Quote('dads_army_dont_panic_mr_mainwaring', 'Don\'t panic #2', SRC_DADS_ARMY, 'don\'t dont panic mr mainwaring'),
  Quote('doctor_who_allonsy_1', 'Allonsy', SRC_DOCTOR_WHO, 'allonsy v2'),
  Quote('doctor_who_allonsy_2', 'Allonsy 2', SRC_DOCTOR_WHO, 'allonsy v2'),
  Quote(
      'friends_atm_vestibule', 'ATM Vestibule', SRC_FRIENDS, 'i am trapped in an atm vestibule with jill goodacre v2'),
  Quote('friends_broke_my_fridge', 'Broke my fridge', SRC_FRIENDS, 'im not talking to you you broke my fridge v2'),
  Quote('friends_18_pages', 'Eighteen pages', SRC_FRIENDS, 'you had rambled on for eighteen pages. Front and back v2'),
  Quote('friends_fell_asleep', 'Fell asleep', SRC_FRIENDS, 'you fell asleep v2'),
  Quote('friends_holiday_armadillo', 'Holiday Armadillo', SRC_FRIENDS, 'im the holiday armadillo v2'),
  Quote('friends_not_even_a_word', 'Not even a word', SRC_FRIENDS, 'thats not even a word v2'),
  Quote('friends_oh_my_god', 'Oh. My. God.', SRC_FRIENDS, 'oh my god v2'),
  Quote('friends_on_a_break', 'On a break', SRC_FRIENDS, 'we were on a break v2'),
  Quote('friends_paper_snow_a_ghost', 'Paper, snow, a ghost!', SRC_FRIENDS, 'paper snow a ghost v2'),
  Quote('friends_pivot', 'Pivot!', SRC_FRIENDS, 'pivot pivaht'),
  Quote('friends_uberweiss', 'Uberweiss!', SRC_FRIENDS, 'uberweiss'),
  Quote('friends_what_the_bleep', 'What the bleep', SRC_FRIENDS, 'what the bleep are ya doing'),
  Quote('ghosts_closer_together', 'Closer together', SRC_GHOSTS, 'we are closer together v2'),
  Quote('ghosts_damn_your_eyes', 'Damn your eyes', SRC_GHOSTS, 'damn your eyes thomas v2', 'ghosts_thomas'),
  Quote('ghosts_kylie_min_ogue', 'Kylie min-ogue', SRC_GHOSTS, 'kylie minogue v2', 'ghosts_thomas'),
  Quote('ghosts_man_on_moonah', 'Man on moonah', SRC_GHOSTS, 'man on moonah v2', 'ghosts_robin'),
  Quote('ghosts_moonah', 'Moonah', SRC_GHOSTS, 'moonah v2', 'ghosts_robin'),
  Quote('ghosts_order', 'Order', SRC_GHOSTS, 'order v2'),
  Quote('ghosts_prawn_go_dooka_dooka', 'Prawn go...', SRC_GHOSTS, 'prawn go dooka gooka v2', 'ghosts_robin'),
  Quote('mandalorian_i_have_spoken', 'I have spoken', SRC_MANDALORIAN, 'i have spoken v2'),
  Quote('mandalorian_i_have_spoken_kuiil', 'I have spoken (Kuiil)', SRC_MANDALORIAN, 'i have spoken v2'),
  Quote('mandalorian_this_is_the_way', 'This is the way', SRC_MANDALORIAN, 'this is the way v2'),
  Quote('star_wars_death_sticks', 'Death sticks', SRC_STAR_WARS, 'you dont want to sell me death sticks v2'),
  Quote('star_wars_its_a_trap', 'It\'s a trap!', SRC_STAR_WARS, 'its a trap v2'),
  Quote('star_wars_order_66', 'Order 66', SRC_STAR_WARS, 'execute order 66 v2'),
  Quote('star_wars_these_arent_the_droids', 'Droids', SRC_STAR_WARS, 'these arent the droids youre looking for v2'),
  Quote(
      'taskmaster_all_the_information', 'All the information', SRC_TASKMASTER, 'all the information is on the task v2'),
  Quote('taskmaster_all_the_information_2', 'All the information 2', SRC_TASKMASTER,
      'all the information is on the task v2'),
  Quote('taskmaster_barge_pole', 'Barge pole', SRC_TASKMASTER, 'one on a barge pole for me v2'),
  Quote('taskmaster_whats_the_situation', 'What\'s the situation?', SRC_TASKMASTER, 'whats the situation v2'),
  Quote('frank_damage', 'I\'ll pay for any damage', SRC_SOME_MOTHERS, 'ill pay for any damage v2'),
  Quote('frank_legs_apart', 'Legs apart', SRC_SOME_MOTHERS, 'legs apart v2'),
  Quote('frank_oh_betty', 'Oh Betty!', SRC_SOME_MOTHERS, 'oh betty v2'),
  Quote('qi_acropolis_1', 'Acopolis 1', SRC_QI, 'they say of the acropolis where the parthenon is v2'),
  Quote('qi_acropolis_2', 'Acopolis 1', SRC_QI, 'they say of the acropolis where the parthenon is v2'),
  Quote('qi_acropolis_3', 'Acopolis 1', SRC_QI, 'they say of the acropolis where the parthenon is v2'),
  Quote('qi_klaxon', 'Klaxon', SRC_QI, 'klaxon v2'),

  // Misc
  Quote('bargain_hunt_swap', 'A negotiated swap', SRC_BARGAIN_HUNT, 'we have a swap we do love a swap negotiated swap'),
  Quote('cabin_pressure_bear_polar', 'Bear Polar', SRC_CABIN_PRESSURE,
      'attention mes amis regardez vouz les bear polars v2'),
  Quote('cabin_pressure_bristol', 'Bristol', SRC_CABIN_PRESSURE, 'we could go to bristol I believe people do'),
  Quote('cabin_pressure_christmas_tree', 'Christmas tree', SRC_CABIN_PRESSURE,
      'oh you come with decorations like a little christmas tree v2'),
  Quote('cabin_pressure_dont_tread_on_me', 'Don\'t tread on me', SRC_CABIN_PRESSURE, 'here i am dont tread on me v2'),
  Quote('cabin_pressure_dragonfruit', 'Dragonfruit', SRC_CABIN_PRESSURE, 'dragonfruit'),
  Quote('cabin_pressure_famously_wrong', 'Famously wrong', SRC_CABIN_PRESSURE,
      'what youve done there arthur is youve taken a fact thats famously wrong and youve got it wrong v2'),
  Quote('cabin_pressure_hat_is_paramount', 'Hat', SRC_CABIN_PRESSURE, 'The hat is paramount v2'),
  Quote('cabin_pressure_jellybabies', 'Jellybabies', SRC_CABIN_PRESSURE, 'Jellybabies to manual jelly babies'),
  Quote('cabin_pressure_lemon', 'Lemon', SRC_CABIN_PRESSURE, 'the lemon is in play'),
  Quote('cabin_pressure_the_master', 'The Master', SRC_CABIN_PRESSURE, 'you see arthur the master v2'),
  Quote('cabin_pressure_never_mind', 'Never mind', SRC_CABIN_PRESSURE, 'never mind martin you lose some dont you'),
  Quote('cabin_pressure_ridiculous_dog', 'Ridiculous dog', SRC_CABIN_PRESSURE,
      'my dog is not ridiculous then whose dog is this'),
  Quote('deal_or_no_deal', 'Deal or no deal?', SRC_DEAL_OR_NO_DEAL, 'deal or no deal v2'),
  Quote('harry_potter_chosen_one', 'The Chosen one', SRC_HARRY_POTTER, 'but i am the chosen one v2'),
  Quote('harry_potter_goblet_of_fire_1', 'The Goblet of Fire (calm)', SRC_HARRY_POTTER,
      'did you put your name in the goblet of fire v2', 'hp_dumbledore'),
  Quote('harry_potter_goblet_of_fire_2', 'The Goblet of Fire (unhinged)', SRC_HARRY_POTTER,
      'did you put your name in the goblet of fire v2', 'hp_dumbledore'),
  Quote('harry_potter_no_ron_no', 'No Ron, no!', SRC_HARRY_POTTER, 'no ron no v2'),
  Quote('harry_potter_not_me', 'Not me', SRC_HARRY_POTTER, 'not me not hermione you v2', 'hp_ron'),
  Quote('harry_potter_pincers', 'Pincers', SRC_HARRY_POTTER, 'pincers click click v2'),
  Quote('harry_potter_what_you_fell_over_for', 'Fell over', SRC_HARRY_POTTER, 'what you fell over for v2'),
  Quote('news_not_another_one', 'Not another one', SRC_NEWS, 'youre joking not another one v2'),
  Quote('ice_age_doesnt_anyone_care', 'Doesn\'t anyone care?', SRC_ICE_AGE,
      'isn\'t there anyone who cares about sid the sloth'),
  Quote('ice_age_im_a_genius', 'I\'m a genius!', SRC_ICE_AGE, 'I\'m im a genius'),
  Quote('ice_age_round_two', 'Who\'s up for round two?', SRC_ICE_AGE, 'whos up for round two 2 v2'),
  Quote('ice_age_they_do_this_every_year', 'Every year', SRC_ICE_AGE, 'they do this every year'),
  Quote('nmj_big_if_horne', 'Big if', SRC_NO_MORE_JOCKEYS, 'big if', 'nmj_horne'),
  Quote('nmj_big_if_key', 'Big if', SRC_NO_MORE_JOCKEYS, 'big if', 'nmj_key'),
  Quote('nmj_big_if_watto', 'Big if', SRC_NO_MORE_JOCKEYS, 'big if', 'nmj_watto'),
  Quote('nmj_bookshelf', 'Bookshelf', SRC_NO_MORE_JOCKEYS, 'dont look at your bookshelf', 'nmj_key'),
  Quote('nmj_does_a_spider_have_a_heart_key', 'Does a spider have a heart?', SRC_NO_MORE_JOCKEYS,
      'does a spider have a heart v2', 'nmj_key'),
  Quote('nmj_does_a_spider_have_a_soul', 'Does a spider have a soul?', SRC_NO_MORE_JOCKEYS,
      'does a spider have a soul v2', 'nmj_watto'),
  Quote('nmj_does_a_spider_have_a_goal', 'Does a spider have a goal?', SRC_NO_MORE_JOCKEYS,
      'does a spider have a goal v2', 'nmj_watto'),
  Quote('nmj_dont_mind_it_horne', 'Don\'t mind it', SRC_NO_MORE_JOCKEYS, 'dont mind it', 'nmj_horne'),
  Quote('nmj_dont_mind_it_watto', 'Don\'t mind it', SRC_NO_MORE_JOCKEYS, 'dont mind it', 'nmj_watto'),
  Quote('nmj_fiddly', 'Fiddly', SRC_NO_MORE_JOCKEYS, 'oh this is fiddly now', 'nmj_watto'),
  Quote('nmj_hand_off_your_face_key', 'Hand off your face', SRC_NO_MORE_JOCKEYS, 'hand off your face', 'nmj_key'),
  Quote('nmj_heard_what_you_have_to_say_horne', 'Heard what you have to say', SRC_NO_MORE_JOCKEYS,
      'ive heard what you have to say', 'nmj_horne'),
  Quote('nmj_heard_what_you_have_to_say_key', 'Heard what you have to say', SRC_NO_MORE_JOCKEYS,
      'ive heard what you have to say', 'nmj_key'),
  Quote('nmj_key_to_play_horne', 'Key to play', SRC_NO_MORE_JOCKEYS, 'key to play', 'nmj_horne'),
  Quote('nmj_key_to_play_watto', 'Key to play', SRC_NO_MORE_JOCKEYS, 'key to play', 'nmj_watto'),
  Quote('nmj_key_to_start_horne', 'Key to start', SRC_NO_MORE_JOCKEYS, 'key to start', 'nmj_horne'),
  Quote('nmj_kitchen_conversions', 'Kitchen Conversions', SRC_NO_MORE_JOCKEYS, 'Woah kitchen conversions', 'nmj_watto'),
  Quote('nmj_lawful_but_awful', 'Lawful but awful', SRC_NO_MORE_JOCKEYS, 'its lawful but its awful', 'nmj_watto'),
  Quote('nmj_mert_aksac_horne', 'Mert Aksac', SRC_NO_MORE_JOCKEYS, 'Mert Aksac', 'nmj_horne'),
  Quote('nmj_mert_aksac_key', 'Mert Aksac', SRC_NO_MORE_JOCKEYS, 'Mert Aksac', 'nmj_key'),
  Quote('nmj_mert_aksac_watto', 'Mert Aksac', SRC_NO_MORE_JOCKEYS, 'Mert Aksac', 'nmj_watto'),
  Quote('nmj_unicorn_mug', 'Boop boop', SRC_NO_MORE_JOCKEYS, 'Boop boop unicorn mug', 'nmj_watto'),
  Quote('nmj_unicorn_mug_2', 'Bop bop', SRC_NO_MORE_JOCKEYS, 'Bop bop unicorn mug', 'nmj_key'),
  Quote('nmj_yet_key', 'Yet', SRC_NO_MORE_JOCKEYS, 'yet', 'nmj_key'),
  Quote('ntnon_come_back_out_again', 'It\'s come out again', SRC_NTNON,
      'would you believe it went in but it\'s its come out again'),
  Quote('ntnon_no_clues', 'No clues!', SRC_NTNON, 'ah no no clues'),
  Quote('lizzie_mcguire_sing_to_me_paulo', 'Sing to me Paulo', SRC_LIZZIE_MCGUIRE, 'sing to me paulo v2'),
  Quote('peter_pan_another_cab', 'Another cab', SRC_PETER_PAN, 'another cab for you mr darling v2'),
  Quote('peter_pan_give_me_the_sword', 'Give me the sword', SRC_PETER_PAN, 'give me the sword v2'),

  // Kids TV
  Quote('noahs_island_oisky_poisky', 'Oisky Poisky', SRC_NOAHS_ISLAND, 'oisky poisky'),
  Quote('art_attack_the_head', 'The Head!', SRC_ART_ATTACK, 'hello its it\'s me again the head'),
  Quote('wallace_no_cheese', 'No cheese Gromit', SRC_WALLACE_AND_GROMIT, 'no cheese gromit not a bit in the house'),
  Quote('wallace_no_crackers', 'No crackers Gromit', SRC_WALLACE_AND_GROMIT,
      'no crackers gromit we\'ve forgotten the crackers'),
  Quote('anastasia_and_id_kick_her_sir', 'And I\'d kick her', SRC_ANASTASIA, 'and id kick her sir v2')
];
