import 'quote.dart';
import 'quote_source.dart';

const List<Quote> ALL_QUOTES = [
  // Sketch
  Quote('nmj_big_if_horne', 'Big if', SRC_NO_MORE_JOCKEYS, 'big if', 'nmj_horne'),
  Quote('nmj_big_if_key', 'Big if', SRC_NO_MORE_JOCKEYS, 'big if', 'nmj_key'),
  Quote('nmj_big_if_watto', 'Big if', SRC_NO_MORE_JOCKEYS, 'big if', 'nmj_watto'),
  Quote('nmj_dont_mind_it_horne', 'Don\'t mind it', SRC_NO_MORE_JOCKEYS, 'dont mind it', 'nmj_horne'),
  Quote('nmj_fiddly', 'Fiddly', SRC_NO_MORE_JOCKEYS, 'oh this is fiddly now', 'nmj_watto'),
  Quote('nmj_key_to_start_horne', 'Key to start', SRC_NO_MORE_JOCKEYS, 'key to start', 'nmj_horne'),
  Quote('nmj_kitchen_conversions', 'Kitchen Conversions', SRC_NO_MORE_JOCKEYS, 'Woah kitchen conversions', 'nmj_watto'),
  Quote('nmj_lawful_but_awful', 'Lawful but awful', SRC_NO_MORE_JOCKEYS, 'its lawful but its awful', 'nmj_watto'),
  Quote('nmj_mert_aksac_horne', 'Mert Aksac', SRC_NO_MORE_JOCKEYS, 'Mert Aksac', 'nmj_horne'),
  Quote('nmj_mert_aksac_key', 'Mert Aksac', SRC_NO_MORE_JOCKEYS, 'Mert Aksac', 'nmj_key'),
  Quote('nmj_mert_aksac_watto', 'Mert Aksac', SRC_NO_MORE_JOCKEYS, 'Mert Aksac', 'nmj_watto'),
  Quote('nmj_unicorn_mug', 'Boop boop', SRC_NO_MORE_JOCKEYS, 'Boop boop unicorn mug', 'nmj_watto'),
  Quote('nmj_unicorn_mug_2', 'Bop bop', SRC_NO_MORE_JOCKEYS, 'Bop bop unicorn mug', 'nmj_key'),
  Quote('nmj_yet_key', 'Yet', SRC_NO_MORE_JOCKEYS, 'yet', 'nmj_key'),
  Quote('ntnon_come_back_out_again', 'It\'s come out again', SRC_NTNON,
      'would you believe it went in but it\'s its come out again'),
  Quote('ntnon_no_clues', 'No clues!', SRC_NTNON, 'ah no no clues'),

  // TV
  Quote('hustle_dodgy_git', 'You dodgy git', SRC_HUSTLE, '30 thirty grand ash danny'),
  Quote('hustle_funny_money', 'Funny money', SRC_HUSTLE, 'None of that funny money'),
  Quote('dexter_hello_dexter_morgan', 'Hello, Dexter Morgan', SRC_DEXTER, 'hello dexter morgan trinity arthur mitchell',
      'trinity'),
  Quote('dexter_more_comfortable', 'More comfortable', SRC_DEXTER,
      'I can get a sandwich if it makes you more comfortable', 'lundy'),
  Quote('dexter_one_o_clock', 'It\'s one o\'clock', SRC_DEXTER,
      'its one o clock i always stop and have lunch at one o clock 1 o clock 1:00', 'lundy'),
  Quote('dexter_pardon_my_tits', 'Pardon my tits', SRC_DEXTER, 'pardon my tits', 'lila'),
  Quote('dexter_reinvent_the_wheel', 'Reinvent the wheel', SRC_DEXTER,
      'maybe you should just learn the basics before you reinvent the damn wheel'),
  Quote('dexter_surprise_motherfucker', 'Surprise', SRC_DEXTER, 'surprise motherfucker motherfucka'),
  Quote('dexter_take_a_picture', 'Take a picture', SRC_DEXTER, 'why dont you take a picture morgan itll last longer'),
  Quote('dexter_tick_tick_tick', 'Tick tick tick', SRC_DEXTER,
      'tick tick tick thats the sound of your life running out', 'dexter_jordan_chase'),
  Quote('dexter_woo_woo_shit', 'Woo woo shit', SRC_DEXTER,
      'angel you keep up with this woo woo shit ima walk right through you'),
  Quote('bean_brace_yourself', 'Brace yourself', SRC_BEAN, 'brace yourself'),
  Quote('bean_fruitcake', 'Fruitcake', SRC_BEAN, 'looks like a fruitcake to me'),
  Quote('bean_im_driving', 'I\'m driving', SRC_BEAN, 'no no no I\'m im driving'),
  Quote('bean_look_at_the_time', 'Look at the time!', SRC_BEAN, 'look at the time'),
  Quote('bean_not_necessarily', 'Not... necessarily', SRC_BEAN, 'not necessarily'),
  Quote('bean_not_that_i_know_of', 'Not that I know of', SRC_BEAN, 'not that I know of'),
  Quote('bean_sunday', 'Sunday!', SRC_BEAN, 'sunday'),
  Quote('bean_very_nice_brian', 'Very nice Brian', SRC_BEAN, 'very nice brian'),
  Quote('b99_bingpot', 'Bingpot!', SRC_B99, 'bingpot'),
  Quote('b99_bingpot_2', 'Bingpot 2', SRC_B99, 'bingpot'),
  Quote('b99_bone', 'Bone', SRC_B99, 'bone'),
  Quote('b99_bone_2', 'Booooone', SRC_B99, 'bone'),
  Quote('b99_boost_my_bottom', 'Boost my bottom', SRC_B99, 'boost my bottom'),
  Quote('b99_hello_dolly', 'Helloooo dolly', SRC_B99, 'hello dolly'),
  Quote('b99_is_everything_ok', 'Is everything ok?', SRC_B99, 'and you ask me is everything okay'),
  Quote('b99_is_everything_ok_2', 'Is everything ok 2', SRC_B99, 'and you ask me is everything okay'),
  Quote('b99_oh_damn', 'Oh damn', SRC_B99, 'oh damn oh damn oh damn'),
  Quote('b99_pain', 'Painnnnn', SRC_B99, 'painnnn'),
  Quote('b99_velvet_thunder', 'Velvet thunder', SRC_B99, 'from now on call me velvet thunderrrr'),
  Quote('b99_vindication', 'Vindication', SRC_B99, 'vindication'),
  Quote('b99_youre_not_cheddar', 'You\'re not cheddar', SRC_B99, 'youre not cheddar youre just some common bitch'),
  Quote('dads_army_dont_like_it_up_em', 'Don\'t like it up \'em', SRC_DADS_ARMY, 'they don\'t dont like it up em'),
  Quote('dads_army_dont_panic_anyone', 'Don\'t panic', SRC_DADS_ARMY, 'don\'t dont panic anyone'),
  Quote('dads_army_dont_panic_mr_mainwaring', 'Don\'t panic #2', SRC_DADS_ARMY, 'don\'t dont panic mr mainwaring'),
  Quote('friends_pivot', 'Pivot!', SRC_FRIENDS, 'pivot pivaht'),
  Quote('friends_uberweiss', 'Uberweiss!', SRC_FRIENDS, 'uberweiss'),
  Quote('friends_what_the_bleep', 'What the bleep', SRC_FRIENDS, 'what the bleep are ya doing'),

  // Misc
  Quote('bargain_hunt_swap', 'A negotiated swap', SRC_BARGAIN_HUNT, 'we have a swap we do love a swap negotiated swap'),
  Quote('ice_age_doesnt_anyone_care', 'Doesn\'t anyone care?', SRC_ICE_AGE,
      'isn\'t there anyone who cares about sid the sloth'),
  Quote('ice_age_im_a_genius', 'I\'m a genius!', SRC_ICE_AGE, 'I\'m im a genius'),
  Quote('ice_age_they_do_this_every_year', 'Every year', SRC_ICE_AGE, 'they do this every year'),

  // Kids TV
  Quote('noahs_island_oisky_poisky', 'Oisky Poisky', SRC_NOAHS_ISLAND, 'oisky poisky'),
  Quote('art_attack_the_head', 'The Head!', SRC_ART_ATTACK, 'hello its it\'s me again the head'),
  Quote('wallace_no_cheese', 'No cheese Gromit', SRC_WALLACE_AND_GROMIT, 'no cheese gromit not a bit in the house'),
  Quote('wallace_no_crackers', 'No crackers Gromit', SRC_WALLACE_AND_GROMIT,
      'no crackers gromit we\'ve forgotten the crackers'),
];
