import 'quote.dart';
import 'quote_source.dart';

const List<Quote> ALL_QUOTES = [
  // Sketch
  Quote('nmj_aksac_horne', 'Mert Aksac', SRC_NO_MORE_JOCKEYS, 'Mert Aksac', 'nmj_horne'),
  Quote('nmj_aksac_key', 'Mert Aksac', SRC_NO_MORE_JOCKEYS, 'Mert Aksac', 'nmj_key'),
  Quote('nmj_aksac_watto', 'Mert Aksac', SRC_NO_MORE_JOCKEYS, 'Mert Aksac', 'nmj_watto'),
  Quote('nmj_kitchen_conversions', 'Kitchen Conversions', SRC_NO_MORE_JOCKEYS, 'Woah kitchen conversions', 'nmj_watto'),
  Quote('nmj_unicorn_mug', 'Boop boop', SRC_NO_MORE_JOCKEYS, 'Boop boop unicorn mug', 'nmj_watto'),
  Quote('nmj_unicorn_mug_2', 'Bop bop', SRC_NO_MORE_JOCKEYS, 'Bop bop unicorn mug', 'nmj_key'),
  Quote('mitchell_bad_miss_1', 'Bad Miss 1', SRC_MITCHELL_AND_WEBB, 'Oh and that\'s a bad miss', 'mitchell_snooker'),
  Quote('mitchell_bad_miss_2', 'Bad Miss 2', SRC_MITCHELL_AND_WEBB, 'Oh and that\'s a bad miss', 'mitchell_snooker'),
  Quote('mitchell_digby_1', 'Dun dunna dun #1', SRC_MITCHELL_AND_WEBB, 'dun dala dun sir digby chicken caesar',
      'mitchell_digby'),
  Quote('mitchell_digby_2', 'Dun dunna dun #2', SRC_MITCHELL_AND_WEBB, 'dun dala dun sir digby chicken caesar',
      'mitchell_digby'),
  Quote('mitchell_expert', 'Expert on wine', SRC_MITCHELL_AND_WEBB,
      'are you even an expert in wine? Because if not I dont know on what basis you presume to order it'),
  Quote('mitchell_i_saw_you', 'I saw you here', SRC_MITCHELL_AND_WEBB, 'i saw you here last week'),
  Quote('mitchell_its_all_in_the_wrist', 'All in the wrist', SRC_MITCHELL_AND_WEBB, 'its all in the wrist'),
  Quote('mitchell_lager_beer', 'Alcoholic lager beer', SRC_MITCHELL_AND_WEBB,
      'This is an alcoholic lager beer isn\'t isnt it John?'),
  Quote('mitchell_petril', 'Petril!', SRC_MITCHELL_AND_WEBB, ''),
  Quote('mitchell_shes_gone', 'She\'s gone sir', SRC_MITCHELL_AND_WEBB, 'shes gone sir theyve all gone and were back'),
  Quote('mitchell_surprising_adventures', 'Surprising Adventures', SRC_MITCHELL_AND_WEBB,
      'yes its the surprising adventures of me sir digby chicken caesar', 'mitchell_digby'),
  Quote('mitchell_tremendous_thirst', 'Tremendous thirst', SRC_MITCHELL_AND_WEBB,
      'I\'ve got a tremendous thirst on all of a sudden'),
  Quote('monty_python_elderberries', 'Elderberries', SRC_MONTY_PYTHON,
      'your mother was a hamster and your father smelled of elderberries'),
  Quote('monty_python_english_pigdogs', 'English pigdogs', SRC_MONTY_PYTHON, 'you do not scare me you english pigdogs'),
  Quote('monty_python_ex_parrot', 'Ex-parrot', SRC_MONTY_PYTHON, 'this is an ex parrot'),
  Quote('monty_python_fart_in_your_general_direction', 'Fart', SRC_MONTY_PYTHON, 'i fart in your general direction'),
  Quote('ntnon_come_back_out_again', 'It\'s come out again', SRC_NTNON,
      'would you believe it went in but it\'s its come out again'),
  Quote('ntnon_no_clues', 'No clues!', SRC_NTNON, 'ah no no clues'),

  // TV
  Quote('hustle_dodgy_git', 'You dodgy git', SRC_HUSTLE, '30 thirty grand ash danny'),
  Quote('hustle_funny_money', 'Funny money', SRC_HUSTLE, 'None of that funny money'),
  Quote(
      'dexter_hello_dexter_morgan', 'Hello, Dexter Morgan', SRC_DEXTER, 'hello dexter morgan trinity arthur mitchell'),
  Quote('dexter_more_comfortable', 'More comfortable', SRC_DEXTER,
      'I can get a sandwich if it makes you more comfortable', 'lundy'),
  Quote('dexter_one_o_clock', 'It\'s one o\'clock', SRC_DEXTER,
      'its one o clock i always stop and have lunch at one o clock 1 o clock 1:00', 'lundy'),
  Quote('dexter_pardon_my_tits', 'Pardon my tits', SRC_DEXTER, 'pardon my tits'),
  Quote('dexter_reinvent_the_wheel', 'Reinvent the wheel', SRC_DEXTER,
      'maybe you should just learn the basics before you reinvent the damn wheel'),
  Quote('dexter_surprise_motherfucker', 'Surprise', SRC_DEXTER, 'surprise motherfucker motherfucka'),
  Quote('dexter_take_a_picture', 'Take a picture', SRC_DEXTER, 'why dont you take a picture morgan itll last longer'),
  Quote(
      'dexter_tick_tick_tick', 'Tick tick tick', SRC_DEXTER, 'tick tick tick thats the sound of your life running out'),
  Quote('dexter_woo_woo_shit', 'Woo woo shit', SRC_DEXTER,
      'angel you keep up with this woo woo shit ima walk right through you'),
  Quote('bean_brace_yourself', 'Brace yourself', SRC_BEAN, 'brace yourself'),
  Quote('bean_fruitcake', 'Fruitcake', SRC_BEAN, 'looks like a fruitcake to me'),
  Quote('bean_im_driving', 'I\'m driving', SRC_BEAN, 'no no no I\'m im driving'),
  Quote('bean_look_at_the_time', 'Look at the time!', SRC_BEAN, 'look at the time'),
  Quote('bean_not_necessarily', 'Not... necessarily', SRC_BEAN, 'not necessarily'),
  Quote('bean_not_that_i_know_of', 'Not that I know of', SRC_BEAN, 'not that I know of'),
  Quote('bean_sunday', 'Sunday!', SRC_BEAN, 'sunday'),
  Quote('bean_very_nice_brian', 'Very nice Brian', SRC_BEAN, 'very nice brian'),
  Quote('b99_bingpot', 'Bingpot!', SRC_B99, 'bingpot'),
  Quote('b99_bingpot_2', 'Bingpot 2', SRC_B99, 'bingpot'),
  Quote('b99_bone', 'Bone', SRC_B99, 'bone'),
  Quote('b99_bone_2', 'Booooone', SRC_B99, 'bone'),
  Quote('b99_boost_my_bottom', 'Boost my bottom', SRC_B99, 'boost my bottom'),
  Quote('b99_hello_dolly', 'Helloooo dolly', SRC_B99, 'hello dolly'),
  Quote('b99_is_everything_ok', 'Is everything ok?', SRC_B99, 'and you ask me is everything okay'),
  Quote('b99_is_everything_ok_2', 'Is everything ok 2', SRC_B99, 'and you ask me is everything okay'),
  Quote('b99_oh_damn', 'Oh damn', SRC_B99, 'oh damn oh damn oh damn'),
  Quote('b99_pain', 'Painnnnn', SRC_B99, 'painnnn'),
  Quote('b99_velvet_thunder', 'Velvet thunder', SRC_B99, 'from now on call me velvet thunderrrr'),
  Quote('b99_vindication', 'Vindication', SRC_B99, 'vindication'),
  Quote('b99_youre_not_cheddar', 'You\'re not cheddar', SRC_B99, 'youre not cheddar youre just some common bitch'),
  Quote('dads_army_dont_like_it_up_em', 'Don\'t like it up \'em', SRC_DADS_ARMY, 'they don\'t dont like it up em'),
  Quote('dads_army_dont_panic_anyone', 'Don\'t panic', SRC_DADS_ARMY, 'don\'t dont panic anyone'),
  Quote('dads_army_dont_panic_mr_mainwaring', 'Don\'t panic #2', SRC_DADS_ARMY, 'don\'t dont panic mr mainwaring'),
  Quote('fawlty_erroneous_dish', 'Erroneous dish', SRC_FAWLTY_TOWERS, 'I have been given an erroneous dish'),
  Quote('fawlty_piece_of_your_brain', 'Piece of your brain', SRC_FAWLTY_TOWERS, 'Is this a piece of your brain Basil'),
  Quote('fawlty_where_did_you_get_it', 'Where did you get it?', SRC_FAWLTY_TOWERS, 'where did you get it Basil'),
  Quote('fawlty_how_did_you_get_it', 'How did you get it?', SRC_FAWLTY_TOWERS,
      'that\'s right i mean how did you get it Fawlty Basil'),
  Quote('friends_uberweiss', 'Uberweiss!', SRC_FRIENDS, 'uberweiss'),
  Quote('hyacinth_blind', 'Thought I\'d gone blind', SRC_HYACINTH, 'thank god for that I thought I\'d gone blind',
      'onslo'),
  Quote('hyacinth_chuffing_heck', 'Chuffing \'eck', SRC_HYACINTH, 'oh chuffing heck eck', 'onslo'),
  Quote('hyacinth_its_bucket', 'It\'s Bucket', SRC_HYACINTH, 'its bouquet try again', 'richard'),
  Quote('hyacinth_kebab', 'Kebab', SRC_HYACINTH, 'i cant handle our hyacinth and a kebab', 'onslo'),
  Quote('hyacinth_lady_of_the_house', 'The Bucket residence', SRC_HYACINTH,
      'the bucket residence lady of the house speaking'),
  Quote('hyacinth_oh_nice', 'Oh nice', SRC_HYACINTH, '', 'onslo'),
  Quote('hyacinth_richard', 'Richard!', SRC_HYACINTH, ''),
  Quote('hyacinth_sheridan', 'Sheridan', SRC_HYACINTH, 'sheridan how lovely of you to call'),
  Quote('hyacinth_sheridan_how_much', 'How much?', SRC_HYACINTH, 'you need how much'),

  // Misc
  Quote('bargain_hunt_swap', 'A negotiated swap', SRC_BARGAIN_HUNT, 'we have a swap we do love a swap negotiated swap'),
  Quote('chase_day_at_the_office', 'Another day at the office', SRC_THE_CHASE, 'just another day at the office shaun'),
  Quote('ice_age_doesnt_anyone_care', 'Doesn\'t anyone care?', SRC_ICE_AGE,
      'isn\'t there anyone who cares about sid the sloth'),
  Quote('ice_age_im_a_genius', 'I\'m a genius!', SRC_ICE_AGE, 'I\'m im a genius'),
  Quote('ice_age_they_do_this_every_year', 'Every year', SRC_ICE_AGE, 'they do this every year'),
  Quote('jonny_english_can_i_help', 'Sorry, can I help?', SRC_JOHNNY_ENGLISH, 'sorry, can I help?'),
  Quote('jonny_english_coiled_viper', 'Coiled viper', SRC_JOHNNY_ENGLISH, 'like a coiled viper he strikes'),
  Quote('jonny_english_i_can_hear_that', 'I can hear that', SRC_JOHNNY_ENGLISH, 'yes i can hear that bough'),
  Quote('jonny_english_i_can_see_that', 'I can see that', SRC_JOHNNY_ENGLISH, 'yes i can see that bough'),
  Quote('jonny_english_just_drop_it', 'Drop it', SRC_JOHNNY_ENGLISH, 'just drop it bough'),
  Quote('jonny_english_just_keep_moving', 'Keep moving', SRC_JOHNNY_ENGLISH,
      'you wont get stuck so long as you keep moving'),
  Quote('jonny_english_musnt_dwell', 'Mustn\'t dwell', SRC_JOHNNY_ENGLISH,
      'you mustnt dwell on your mistakes bough. you must learn from them and move on'),
  Quote('jonny_english_no_please', 'No please', SRC_JOHNNY_ENGLISH, 'no please no no no please no please'),
  Quote('jonny_english_no_thank_you', 'No thank you', SRC_JOHNNY_ENGLISH, 'thank you bough but no thank you'),
  Quote('jonny_english_pegasus', 'Pegasus!', SRC_JOHNNY_ENGLISH, 'we must report to pegasus'),
  Quote('jonny_english_poo_tube', 'Poo tube', SRC_JOHNNY_ENGLISH,
      'i dont know why you climbed up that awful poo tube when there was a perfectly good ladder right beside it'),

  // Kids TV
  Quote('rat_race_hope_i_win', 'I hope I win', SRC_RAT_RACE, 'a race I hope i win'),
  Quote('rat_race_im_winning', 'I\'m winning', SRC_RAT_RACE, 'a race a race im winning im winning'),
  Quote('rat_race_screwed', 'I make joke', SRC_RAT_RACE, 'I make joke to help you forget how screwed you are'),
  Quote('noahs_island_oisky_poisky', 'Oisky Poisky', SRC_NOAHS_ISLAND, 'oisky poisky'),
  Quote('art_attack_the_head', 'The Head!', SRC_ART_ATTACK, 'hello its it\'s me again the head'),
  Quote('wallace_no_cheese', 'No cheese Gromit', SRC_WALLACE_AND_GROMIT, 'no cheese gromit not a bit in the house'),
  Quote('wallace_no_crackers', 'No crackers Gromit', SRC_WALLACE_AND_GROMIT,
      'no crackers gromit we\'ve forgotten the crackers'),
];
